
package br.ufc.front.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CoreServicesParserConfigurationException", targetNamespace = "http://webservices.storm.ufc.br")
public class CoreServicesParserConfigurationException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CoreServicesParserConfigurationException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CoreServicesParserConfigurationException_Exception(String message, CoreServicesParserConfigurationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CoreServicesParserConfigurationException_Exception(String message, CoreServicesParserConfigurationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservice.CoreServicesParserConfigurationException
     */
    public CoreServicesParserConfigurationException getFaultInfo() {
        return faultInfo;
    }

}
