
package br.ufc.hpc.frontend.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CoreServices", targetNamespace = "http://webservices.storm.ufc.br", wsdlLocation = "http://storm.lia.ufc.br:8080/axis2/services/CoreServices?wsdl")
public class CoreServices
    extends Service
{

    private final static URL CORESERVICES_WSDL_LOCATION;
    private final static WebServiceException CORESERVICES_EXCEPTION;
    private final static QName CORESERVICES_QNAME = new QName("http://webservices.storm.ufc.br", "CoreServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://storm.lia.ufc.br:8080/axis2/services/CoreServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CORESERVICES_WSDL_LOCATION = url;
        CORESERVICES_EXCEPTION = e;
    }

    public CoreServices() {
        super(__getWsdlLocation(), CORESERVICES_QNAME);
    }

    public CoreServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), CORESERVICES_QNAME, features);
    }

    public CoreServices(URL wsdlLocation) {
        super(wsdlLocation, CORESERVICES_QNAME);
    }

    public CoreServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CORESERVICES_QNAME, features);
    }

    public CoreServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoreServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CoreServicesPortType
     */
    @WebEndpoint(name = "CoreServicesHttpSoap11Endpoint")
    public CoreServicesPortType getCoreServicesHttpSoap11Endpoint() {
        return super.getPort(new QName("http://webservices.storm.ufc.br", "CoreServicesHttpSoap11Endpoint"), CoreServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoreServicesPortType
     */
    @WebEndpoint(name = "CoreServicesHttpSoap11Endpoint")
    public CoreServicesPortType getCoreServicesHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.storm.ufc.br", "CoreServicesHttpSoap11Endpoint"), CoreServicesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CORESERVICES_EXCEPTION!= null) {
            throw CORESERVICES_EXCEPTION;
        }
        return CORESERVICES_WSDL_LOCATION;
    }

}
