
package br.ufc.hpc.frontend.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CoreServicesIOException", targetNamespace = "http://webservices.storm.ufc.br")
public class CoreServicesIOException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CoreServicesIOException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CoreServicesIOException_Exception(String message, CoreServicesIOException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CoreServicesIOException_Exception(String message, CoreServicesIOException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservice.CoreServicesIOException
     */
    public CoreServicesIOException getFaultInfo() {
        return faultInfo;
    }

}
